const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  ADD_RESTAURANT_SUCCESS: "ADD_RESTAURANT_SUCCESS",

  //admin
  FETCH_PROVINCE_START: "FETCH_PROVINCE_START",
  FETCH_PROVINCE_SUCCESS: "FETCH_PROVINCE_SUCCESS",
  FETCH_PROVINCE_FAILED: "FETCH_PROVINCE_FAILED",

  FETCH_PRICE_SUCCESS: "FETCH_PRICE_SUCCESS",
  FETCH_PRICE_FAILED: "FETCH_PRICE_FAILED",

  FETCH_PAYMENT_SUCCESS: "FETCH_PAYMENT_SUCCESS",
  FETCH_PAYMENT_FAILED: "FETCH_PAYMENT_FAILED",

  FETCH_PRICE_START: "FETCH_PRICE_START",
  FETCH_PAYMENT_START: "FETCH_PAYMENT_START",

  CREATE_RESTAURANT_SUCCESS: "CREATE_RESTAURANT_SUCCESS",
  CREATE_RESTAURANT_FAILED: "CREATE_RESTAURANT_FAILED",

  DELETE_RESTAURANT_SUCCESS: "DELETE_RESTAURANT_SUCCESS",
  DELETE_RESTAURANT_FAILED: "DELETE_RESTAURANT_FAILED",

  EDIT_RESTAURANT_SUCCESS: "EDIT_RESTAURANT_SUCCESS",
  EDIT_RESTAURANT_FAILED: "EDIT_RESTAURANT_FAILED",

  FETCH_ALL_RESTAURANTS_SUCCESS: "FETCH_ALL_RESTAURANTS_SUCCESS",
  FETCH_ALL_RESTAURANTS_FAILED: "FETCH_ALL_RESTAURANTS_FAILED",

  FETCH_TOP_RESTAURANT_SUCCESS: "FETCH_TOP_RESTAURANT_SUCCESS",
  FETCH_TOP_RESTAURANT_FAILED: "FETCH_TOP_RESTAURANT_FAILED",

  FETCH_ALL_RESTAURANT_NAMES_SUCCESS: "FETCH_ALL_RESTAURANT_NAMES_SUCCESS",
  FETCH_ALL_RESTAURANT_NAMES_FAILED: "FETCH_ALL_RESTAURANT_NAMES_FAILED",

  SAVE_DETAIL_RESTAURANT_SUCCESS: "SAVE_DETAIL_RESTAURANT_SUCCESS",
  SAVE_DETAIL_RESTAURANT_FAILED: "SAVE_DETAIL_RESTAURANT_FAILED",

  FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: "FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_TIME_FAILED: "FETCH_ALLCODE_SCHEDULE_TIME_FAILED",

  FETCH_ALL_TYPE_NAMES_SUCCESS: "FETCH_ALL_TYPE_NAMES_SUCCESS",
  FETCH_ALL_TYPE_NAMES_FAILED: "FETCH_ALL_TYPE_NAMES_FAILED",
});

export default actionTypes;
